export const siteData = {
  opening: { label: "PRÓXIMA APERTURA", area: "POPOTLA · CDMX", schedule: "LUN — VIE · 8:00 — 20:00" },
  navigation: [
    { href: "#nosotros", label: "QUIÉNES SOMOS" },
    { href: "/menu", label: "MENÚ" },
    { href: "/experiencia", label: "EXPERIENCIA" },
    { href: "/eventos", label: "EVENTOS" },
    { href: "#contacto", label: "CONTACTO" },
    { href: "#preguntas-frecuentes", label: "PREGUNTAS FRECUENTES" },
  ],
  navCta: "QUIERO IR",
  hero: {
    eyebrow: "KALLISTA CAFÉ · POPOTLA",
    title: ["VEN POR", "EL CAFÉ.", "QUÉDATE POR", "EL MOMENTO."],
    intro: "Café de especialidad, algo delicioso y un lugar pet friendly con Wi-Fi para compartir, trabajar o disfrutar tu tiempo en Popotla, CDMX. Bienvenido a KALLISTA CAFÉ.",
    ctaPrimary: "CONOCE EL MENÚ", ctaSecondary: "CÓMO LLEGAR",
    artLabel: ["CAFÉ", "AMIGOS", "TIEMPO DE CALIDAD"], stickerTop: "HECHO CON", stickerBottom: "CARIÑO",
    mood: "SIÉNTETE EN CASA", imageAlt: "Café, bebida y pan dulce servidos en una mesa de KALLISTA Café",
  },
  ticker: ["CAFÉ", "DESAYUNO", "WI-FI", "PET FRIENDLY", "AMIGOS", "EVENTOS", "TIEMPO DE CALIDAD"],
  about: {
    kicker: "CONÓCENOS",
    title: ["SOMOS", "KALLISTA CAFÉ."],
    lead: "Un nombre griego para celebrar la belleza de los momentos cotidianos.",
    body: "El nombre KALLISTA CAFÉ toma KALLISTA del griego κάλλιστα (kállista), una palabra que expresa hacer o vivir algo «de la mejor y más bella manera». Elegimos este nombre porque creemos que la belleza no tiene que ser solemne: aparece en un café bien hecho, algo rico, una conversación y el tiempo compartido. KALLISTA CAFÉ es nuestra promesa de cuidar cada detalle para convertir lo cotidiano en un buen momento.",
    signature: "KALLISTA CAFÉ: lo cotidiano, de la manera más bella.",
    values: ["CAFÉ CON CARIÑO", "COMIDA PARA DISFRUTAR", "ESPACIO PARA TODXS"],
  },
  menu: {
    kicker: "ALGO RICO PARA TI", title: ["ELIGE TU", "ANTOJO."],
    note: "Bebidas con personalidad, café bien hecho y algo delicioso para acompañar tu momento.",
    sliderLabel: "Fotos de los platillos y bebidas de KALLISTA Café",
    imageAlt: "Platillo o bebida servido en KALLISTA Café, foto",
    previousLabel: "Ver la foto anterior",
    nextLabel: "Ver la foto siguiente",
    footnote: "Consulta el menú completo para descubrir crepas, waffles, desayunos, ensaladas, baguettes, bebidas y opciones infantiles.",
  },
  place: {
    kicker: "TIEMPO DE CALIDAD", title: ["UN LUGAR PARA", "DISFRUTAR", "TU TIEMPO"],
    body: "Ven a trabajar, desayunar, compartir algo rico, encontrarte con amigos o hacer una pausa en Popotla, CDMX. KALLISTA CAFÉ quiere convertirse en ese lugar al que siempre tienes ganas de volver.",
    origin: "KALLISTA CAFÉ toma su nombre del griego κάλλιστα: hacer las cosas de la mejor y más bella manera.",
    perks: [
      { icon: "⌁", label: "WI-FI" },
      { icon: "♡", label: "PET FRIENDLY" },
      { icon: "✎", label: "PARA TRABAJAR" },
      { icon: "☻", label: "PARA COMPARTIR" },
      { icon: "☕", label: "CAFÉ Y COMIDA RICA" },
    ],
  },
  events: {
    kicker: "LA COMUNIDAD SE ENCUENTRA", title: ["EVENTOS EN", "KALLISTA CAFÉ"], status: "PRÓXIMAMENTE", shortStatus: "PRONTO",
    description: "Estamos preparando encuentros para compartir, descubrir y pasarla bien juntos.", cta: "VER PRÓXIMOS EVENTOS",
  },
  wifi: {
    kicker: "WI-FI DE CORTESÍA", title: "CONÉCTATE.",
    body: "Escanea el código QR con la cámara de tu teléfono para conectarte a nuestro Wi-Fi.",
    networkLabel: "RED", network: "INFINITUM23B1", note: "DISPONIBLE DURANTE TU VISITA",
    imageAlt: "Código QR para conectarse al Wi-Fi de KALLISTA Café",
  },
  visit: {
    kicker: "HABLEMOS", title: ["CONTACTA", "CON NOSOTROS."], area: "Mar Negro 204, Popotla",
    city: "Miguel Hidalgo, CDMX", scheduleLabel: "HORARIO", schedule: ["Lunes a viernes", "8:00 a 20:00"],
    mapsLabel: "ABRIR EN MAPAS", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Mar+Negro+204%2C+Popotla%2C+Miguel+Hidalgo%2C+CDMX",
    mapTitle: "Ubicación de KALLISTA Café en Google Maps",
    mapEmbedUrl: "https://www.google.com/maps?q=Mar+Negro+204%2C+Popotla%2C+Miguel+Hidalgo%2C+CDMX&output=embed",
    form: {
      name: "NOMBRE", email: "CORREO ELECTRÓNICO", phone: "TELÉFONO (OPCIONAL)", message: "MENSAJE",
      namePlaceholder: "Tu nombre", emailPlaceholder: "tu@correo.com", phonePlaceholder: "+52 55 0000 0000",
      messagePlaceholder: "¿Cómo podemos ayudarte?", submit: "ENVIAR MENSAJE",
    },
  },
  faq: {
    kicker: "ANTES DE VENIR", title: ["PREGUNTAS", "FRECUENTES."],
    items: [
      { question: "¿Dónde está KALLISTA CAFÉ?", answer: "Estamos en Mar Negro 204, Popotla, Miguel Hidalgo, CDMX." },
      { question: "¿Cuál es el horario?", answer: "Abrimos de lunes a viernes, de 8:00 a 20:00." },
      { question: "¿Tienen Wi-Fi y espacio para trabajar?", answer: "Sí. Contamos con Wi-Fi y un espacio cómodo para trabajar, hacer una pausa o reunirte." },
      { question: "¿KALLISTA CAFÉ es pet friendly?", answer: "Sí, tus mascotas son bienvenidas. Te pedimos mantenerlas contigo y cuidar la comodidad de todas las personas." },
      { question: "¿Organizan eventos?", answer: "Estamos preparando encuentros y actividades para la comunidad. Publicaremos las próximas fechas en el sitio y en Instagram." },
    ],
  },
  final: {
    instagramHandle: "@KALLISTA.CAFE", title: ["CAFÉ RICO.", "TIEMPO BIEN VIVIDO."],
    cta: "SÍGUENOS EN INSTAGRAM", instagramUrl: "https://instagram.com/kallista.cafe",
  },
  footer: {
    line1: "MAR NEGRO 204 · POPOTLA · CDMX", line2: "CAFÉ · COMUNIDAD · TIEMPO DE CALIDAD", privacy: "AVISO DE PRIVACIDAD",
    keywords: [
      { label: "KALLISTA Café CDMX", href: "/" }, { label: "café en Popotla CDMX", href: "/" },
      { label: "cafetería en Popotla CDMX", href: "/" }, { label: "café en Miguel Hidalgo CDMX", href: "/" },
      { label: "café de especialidad CDMX", href: "/menu" }, { label: "desayuno en Popotla CDMX", href: "/menu" },
      { label: "crepas en Popotla", href: "/menu#crepas" }, { label: "waffles en Popotla", href: "/menu#comida" },
      { label: "matcha en CDMX", href: "/menu#bebidas" }, { label: "menú infantil cafetería", href: "/menu#pequenos" },
      { label: "café pet friendly CDMX", href: "/experiencia" }, { label: "café con Wi-Fi CDMX", href: "/experiencia" },
      { label: "café para trabajar CDMX", href: "/experiencia" }, { label: "lugar para desayunar en Popotla", href: "/experiencia" },
      { label: "eventos en cafetería CDMX", href: "/eventos" }, { label: "cafetería en Mar Negro 204", href: "/#contacto" },
    ],
  },
} as const;
