export const siteDataEn = {
  opening: { label: "OPENING SOON", area: "POPOTLA · MEXICO CITY", schedule: "MON — FRI · 8:00 — 20:00" },
  navigation: [
    { href: "#nosotros", label: "WHO WE ARE" },
    { href: "/en/menu", label: "MENU" },
    { href: "/en/experience", label: "EXPERIENCE" },
    { href: "/en/events", label: "EVENTS" },
    { href: "#contacto", label: "CONTACT" },
    { href: "#preguntas-frecuentes", label: "FAQ" },
  ],
  navCta: "LET'S GO",
  hero: {
    eyebrow: "KALLISTA CAFÉ · POPOTLA",
    title: ["COME FOR", "THE COFFEE.", "STAY FOR", "THE MOMENT."],
    intro: "Specialty coffee, something delicious, and a pet-friendly place with Wi-Fi to share, work, or enjoy your time in Popotla, CDMX. Welcome to KALLISTA CAFÉ.",
    ctaPrimary: "EXPLORE THE MENU", ctaSecondary: "HOW TO GET HERE",
    artLabel: ["COFFEE", "FRIENDS", "QUALITY TIME"], stickerTop: "MADE WITH", stickerBottom: "CARE",
    mood: "MAKE YOURSELF AT HOME", imageAlt: "Coffee, a refreshing drink, and pastries served at KALLISTA Café",
  },
  ticker: ["COFFEE", "BREAKFAST", "WI-FI", "PET FRIENDLY", "FRIENDS", "EVENTS", "QUALITY TIME"],
  about: {
    kicker: "GET TO KNOW US",
    title: ["WE ARE", "KALLISTA CAFÉ."],
    lead: "A Greek name that celebrates the beauty of everyday moments.",
    body: "The name KALLISTA CAFÉ takes KALLISTA from the Greek κάλλιστα (kállista), a word that expresses doing or living something “in the best and most beautiful way.” We chose it because beauty does not have to be formal: it lives in a well-made coffee, something delicious, a conversation, and time shared together. KALLISTA CAFÉ is our simple promise to care about every detail and turn the everyday into a good moment.",
    signature: "KALLISTA CAFÉ: everyday life, in its most beautiful form.",
    values: ["COFFEE MADE WITH CARE", "FOOD TO ENJOY", "A PLACE FOR EVERYONE"],
  },
  menu: {
    kicker: "SOMETHING DELICIOUS FOR YOU", title: ["CHOOSE YOUR", "CRAVING."],
    note: "Drinks with personality, carefully brewed coffee, and something delicious to make the moment complete.",
    items: [
      { number: "01", name: "AMERICANO", detail: "Freshly brewed coffee", price: "$50", className: "sky" },
      { number: "02", name: "ICED LATTE", detail: "House specialty", price: "$95", className: "coffee" },
      { number: "03", name: "MATCHA LATTE", detail: "Matcha · milk", price: "$85", className: "matcha" },
    ],
    footnote: "Explore the full menu for crêpes, waffles, breakfast, salads, baguettes, drinks, and kids’ options.",
  },
  place: {
    kicker: "QUALITY TIME", title: ["A PLACE TO", "ENJOY", "YOUR TIME"],
    body: "Come to work, have breakfast, share something delicious, meet friends, or take a break in Popotla, CDMX. KALLISTA CAFÉ wants to become the place you always feel like coming back to.",
    origin: "KALLISTA CAFÉ takes its name from the Greek κάλλιστα: doing things in the best and most beautiful way.",
    perks: [
      { icon: "⌁", label: "WI-FI" }, { icon: "♡", label: "PET FRIENDLY" },
      { icon: "✎", label: "WORK FRIENDLY" }, { icon: "☻", label: "A PLACE TO SHARE" },
      { icon: "☕", label: "GREAT COFFEE & FOOD" },
    ],
  },
  events: {
    kicker: "WHERE THE COMMUNITY MEETS", title: ["EVENTS AT", "KALLISTA CAFÉ"], status: "COMING SOON", shortStatus: "SOON",
    description: "We are preparing gatherings where we can share, discover, and have a great time together.", cta: "VIEW UPCOMING EVENTS",
  },
  club: {
    brand: "KALLISTA CAFÉ\nCLUB", subtitle: "A GROWING\nCOMMUNITY", note: "FOR REGULARS · FRIENDS · EVENTS",
    member: "COMING SOON", tagline: "COME FOR THE COFFEE.\nCOME BACK FOR THE PEOPLE.",
  },
  visit: {
    kicker: "LET'S TALK", title: ["GET IN", "TOUCH."], area: "Mar Negro 204, Popotla",
    city: "Miguel Hidalgo, Mexico City", scheduleLabel: "HOURS", schedule: ["Monday to Friday", "8:00 to 20:00"],
    mapsLabel: "OPEN IN MAPS", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Mar+Negro+204%2C+Popotla%2C+Miguel+Hidalgo%2C+CDMX",
    mapTitle: "KALLISTA Café location on Google Maps",
    mapEmbedUrl: "https://www.google.com/maps?q=Mar+Negro+204%2C+Popotla%2C+Miguel+Hidalgo%2C+CDMX&output=embed",
    form: {
      name: "NAME", email: "EMAIL", phone: "PHONE (OPTIONAL)", message: "MESSAGE",
      namePlaceholder: "Your name", emailPlaceholder: "you@email.com", phonePlaceholder: "+52 55 0000 0000",
      messagePlaceholder: "How can we help?", submit: "SEND MESSAGE",
    },
  },
  faq: {
    kicker: "BEFORE YOU VISIT", title: ["FREQUENTLY ASKED", "QUESTIONS."],
    items: [
      { question: "Where is KALLISTA CAFÉ?", answer: "We are at Mar Negro 204, Popotla, Miguel Hidalgo, CDMX." },
      { question: "What are your opening hours?", answer: "We are open Monday through Friday, from 8:00 to 20:00." },
      { question: "Do you have Wi-Fi and space to work?", answer: "Yes. We offer Wi-Fi and a comfortable space to work, take a break, or meet up." },
      { question: "Is KALLISTA CAFÉ pet friendly?", answer: "Yes, pets are welcome. Please keep them with you and be mindful of everyone’s comfort." },
      { question: "Do you host events?", answer: "We are preparing gatherings and activities for the community. Upcoming dates will be shared here and on Instagram." },
    ],
  },
  final: {
    instagramHandle: "@KALLISTA.CAFE", title: ["GREAT COFFEE.", "TIME WELL SPENT."],
    cta: "FOLLOW US ON INSTAGRAM", instagramUrl: "https://instagram.com/kallista.cafe",
  },
  footer: {
    line1: "MAR NEGRO 204 · POPOTLA · MEXICO CITY", line2: "COFFEE · COMMUNITY · QUALITY TIME", privacy: "PRIVACY NOTICE",
    keywords: [
      { label: "KALLISTA Café CDMX", href: "/en" }, { label: "coffee shop Popotla CDMX", href: "/en" },
      { label: "coffee shop Miguel Hidalgo CDMX", href: "/en" }, { label: "specialty coffee CDMX", href: "/en/menu" },
      { label: "breakfast in Popotla CDMX", href: "/en/menu" }, { label: "crêpes in Popotla", href: "/en/menu#crepas" },
      { label: "waffles in Popotla", href: "/en/menu#comida" }, { label: "matcha in CDMX", href: "/en/menu#bebidas" },
      { label: "kids’ coffee shop menu", href: "/en/menu#pequenos" }, { label: "pet-friendly coffee shop CDMX", href: "/en/experience" },
      { label: "coffee shop with Wi-Fi CDMX", href: "/en/experience" }, { label: "coffee shop to work from CDMX", href: "/en/experience" },
      { label: "breakfast place in Popotla", href: "/en/experience" }, { label: "coffee shop events CDMX", href: "/en/events" },
      { label: "coffee shop at Mar Negro 204", href: "/en#contacto" },
    ],
  },
} as const;
